### ISSUE TITLE
有些问题烦请作者回复

### ISSUE THREAD

**Issue by 1073535050** [SuminHan/Traffic-UAGCRNTF#1]
作者你好，在拜读你的论文之后，我发现在配置虚拟环境时，运行这段python train.py --model_name=MyUAGCTransformer --dataset=metr-la --Q=12 --activity_embedding --sensor_embedding --graph_type=cooccur_dist代码时，会出现报错python train.py --model_name=MyUAGCTransformer --dataset=metr-la --Q=12 --activity_embedding --sensor_embedding --graph_type=cooccur_dist提示我输入数据不对，烦请作者回复一下疑问，万分感谢

**Comment by 1073535050** [comment]
在运行train.py时同样遇到报错File "/data/jupyterlab/dybcikm/code/train.py", line 84, in <module>
    assert args.Q == 9
AssertionError

**Comment by SuminHan** [comment]
I think you executed with PEMSD7 data. You can run with --Q=12 with METR-LA and PEMS-BAY data though, you can load them from original DCRNN author: https://github.com/liyaguang/DCRNN. Sorry for late reply.

**Comment by SuminHan** [comment]
I just uploaded original dataset here https://www.dropbox.com/scl/fi/6wlfzqjl9ix2v4m453stv/dataset.zip?rlkey=lchozhd93f7siffcuc9ec5kgk&st=32wb508j&dl=0 feel free to check.
